[workspace]
[package]
edition = "2021"
name = "token-mozakvm"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../sdk" }
rkyv = { version = "=0.8.0-alpha.1", default-features = false, features = ["pointer_width_32", "alloc", "bytecheck"] }
rkyv_derive = "=0.8.0-alpha.1"
token-core-logic = { path = "../core-logic" }
wallet-core-logic = { path = "../../wallet/core-logic" }

[features]
std = []

# The following is read by `run_examples.py`
[package.metadata.mozak]
example_dependents = ["wallet"]
example_program_id = "MZK-63236d3b0bc73b9cb18ab2aacbbcf741b84d0560e00172374ddfcffea7b409cc"
