[workspace]
[package]
edition = "2021"
name = "memory-access-mozakvm"
version = "0.1.0"

[dependencies]
mozak-sdk = { path = "../../../sdk", default-features = false }

[features]
std = ["mozak-sdk/default"]
