[book]
authors = ["Mozak Team"]
description = "A book about Mozak Zero-Knowledge RISC-V Virtual Machine"
language = "en"
multilingual = false
src = "book"
title = "Mozak-VM"

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/0xmozak/mozak-vm"
mathjax-support = true

[build]
build-dir = "target/book"
