[package]
edition = "2021"
name = "fibonacci-input"
version = "0.1.0"

[target.'cfg(target_os="zkvm")'.dependencies.guest]
features = ["std"]
path = "../../guest"

[dependencies]
guest = { path = "../../guest" }

[[bin]]
name = "fibonacci-input"
path = "main.rs"
