[package]
name = "inputtape-mozakvm"
version = "0.1.0"
edition = "2021"

[dependencies]
inputtape-core-logic = { path = "../core-logic"}
mozak-sdk = {path = "../../../sdk"}

[features]
std = []

# The following is read by `run_examples.py`
[package.metadata.mozak]
example_program_id = "MZK-5de9bc1bb4cb7a9f9cf991a32230d014b44274ea5464a352f089a8cccc486915"
