[package]
edition = "2021"
name = "counter-native"
version = "0.1.0"

[dependencies]
counter-core-logic = { path = "../core-logic" }
counter-elf-data = { path = "../elf-data" }
mozak-sdk = { path = "../../../sdk" }
rkyv = { version = "=0.8.0-alpha.1", default-features = false, features = [
  "pointer_width_32",
  "alloc",
] }
