name: Labeler
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

permissions:
  pull-requests: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: github/issue-labeler@v3.3
        id: issue-labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/actions/labeler.yml
          enable-versioned-regex: 0
          sync-labels: 1

      - name: Create documentation issue
        if: ${{ steps.issue-labeler.outputs.labels-added }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: new-migrated-issue.yml
          repo: mozak/doc-issues
          ref: main
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          inputs: '{ "pr-number": "${{ github.event.pull_request.number }}" }'

      - name: Close documentation issue
        if: ${{ steps.issue-labeler.outputs.labels-removed }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: delete-migrated-issue.yml
          repo: mozak/doc-issues
          ref: main
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          inputs: '{ "pr-number": "${{ github.event.pull_request.number }}" }'
