[package]
edition = "2021"
name = "wallet"
version = "0.1.0"

[features]
native = []
std = [] # TODO: ðŸ˜± why this black magick works?

[dependencies]
mozak-sdk = { path = "../../sdk" }
rkyv = { version = "=0.8.0-alpha.1", default-features = false, features = ["pointer_width_32", "alloc", "bytecheck"] }
rkyv_derive = "=0.8.0-alpha.1"

[target.'cfg(not(target_os="mozakvm"))'.dependencies]
hex = "0.4"
rand = "0.8"
rand_chacha = "0.3"

[[bin]]
name = "walletbin"
path = "main_mozak.rs"

[[bin]]
name = "wallet-native"
path = "main_native.rs"
required-features = ["native"]

[lib]
name = "wallet"
path = "core_logic.rs"

# The following is read by `run_examples.py`
[package.metadata.mozak]
example_program_id = "MZK-c51b8a31c98b9fe13065b485c9f8658c194c430843570ccac2720a3b30b47adb"
